- hosts: www
  vars:
    days_to_keep_logs: 365
  sudo: yes

  tasks:

  #---------------------------------------------------------------------------
  #
  #                           L O G   R O T A T I O N 
  #
  #---------------------------------------------------------------------------

  - replace:  dest=/etc/logrotate.d/syslog-ng  regexp='^([ \t]\*)weekly[ \t]*$' replace='\1daily'
  - replace:  dest=/etc/logrotate.d/ufw        regexp='^([ \t]*)weekly[ \t]*$'  replace='\1daily'
  - replace:  dest=/etc/logrotate.d/dpkg       regexp='^([ \t]*)monthly[ \t]*$' replace='\1daily'
  - replace:  dest=/etc/logrotate.d/syslog-ng  regexp='^([ \t]*)rotate[ \t]*$'  replace='\1rotate {{ days_to_keep_logs }}'
  - replace:  dest=/etc/logrotate.d/ufw        regexp='^([ \t]*)rotate[ \t]*$'  replace='\1rotate {{ days_to_keep_logs }}'
  - replace:  dest=/etc/logrotate.d/dpkg       regexp='^([ \t]*)rotate[ \t]*$'  replace='\1rotate {{ days_to_keep_logs }}'
 

  #---------------------------------------------------------------------------
  #
  #                              S Y S L O G - N G
  #
  #---------------------------------------------------------------------------

  - copy:  src= syslog-ng.conf.tinyvz  dest=/etc/syslog-ng/syslog-ng.conf  backup=yes  owner=root  group=root  mode=644


  #---------------------------------------------------------------------------
  #
  #                            C O P Y   F I L E S 
  #
  #---------------------------------------------------------------------------

  - file:  path=/root/bin  state=directory           group=root  owner=root  mode=755
  - copy:  src=stoplist    dest=/root/bin/stoplist   owner=root  group=root  mode=644
  - copy:  src=stopfiles   dest=/root/bin/stopfiles  owner=root  group=root  mode=644
  - copy:  src=ai.sh       dest=/root/bin/ai.sh      owner=root  group=root  mode=755


  #---------------------------------------------------------------------------
  #
  #                           P U T   I N   C R O N 
  #
  # Run before logrotate:
  #
  #      # grep cron.daily /etc/crontab
  #      45 5 * * * root test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
  #
  #---------------------------------------------------------------------------

  - cron: user=root name="Artificial Ignorance" hour="4" minute="23" job="/root/bin/ai.sh"
