- hosts: www
  vars:
    env: tinyvz
    usr: logbot
  sudo: yes

  tasks:

  #---------------------------------------------------------------------------
  #
  #                                U S E R
  #
  # By default, Ubuntu Lucid only lets the adm group read the logs and
  # /dev/xconsole.  Perfect for what the ai logbot does.
  #
  #---------------------------------------------------------------------------

  - user:  name={{usr}}                group=adm        createhome=yes
  - file:  path=/home/{{usr}}/offsets  state=directory  group=adm       owner=logbot  mode=750
  - file:  path=/home/{{usr}}/bin      state=directory  group=adm       owner=logbot  mode=755

  #---------------------------------------------------------------------------
  #
  #                            C O P Y   F I L E S
  #
  #---------------------------------------------------------------------------

  - copy:  src=stoplist.{{env}}   dest=/home/{{usr}}/bin/stoplist   owner=logbot  group=adm  mode=644
  - copy:  src=stopfiles.{{env}}  dest=/home/{{usr}}/bin/stopfiles  owner=logbot  group=adm  mode=644
  - copy:  src=ai.sh              dest=/home/{{usr}}/bin/ai.sh      owner=logbot  group=adm  mode=755


  #---------------------------------------------------------------------------
  #
  #                           P U T   I N   C R O N
  #
  #---------------------------------------------------------------------------

  - cron: user=logbot name="Artificial Ignorance" minute="0" job="/home/{{usr}}/bin/ai.sh"
