- hosts: www
  vars:
    env: tinyvz
  sudo: yes

  tasks:

  #---------------------------------------------------------------------------
  #
  #                            C O P Y   F I L E S
  #
  #---------------------------------------------------------------------------

  - file:  path=/root/bin         state=directory           group=root  owner=root  mode=755
  - file:  path=/root/retail      state=directory           group=root  owner=root  mode=700
  - copy:  src=stoplist.{{env}}   dest=/root/bin/stoplist   owner=root  group=root  mode=644
  - copy:  src=stopfiles.{{env}}  dest=/root/bin/stopfiles  owner=root  group=root  mode=644
  - copy:  src=ai.sh              dest=/root/bin/ai.sh      owner=root  group=root  mode=755


  #---------------------------------------------------------------------------
  #
  #                           P U T   I N   C R O N
  #
  # Run before logrotate:
  #
  #      # grep cron.daily /etc/crontab
  #      45 5 * * * root test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
  #
  #---------------------------------------------------------------------------

  - cron: user=root name="Artificial Ignorance" hour="4" minute="23" job="/root/bin/ai.sh"
